"""
Helper script to build EDA_and_Training.ipynb programmatically.
Run: python notebooks/build_notebook.py
"""
import json, os

def md(source):
    if isinstance(source, list):
        source = "".join(source)
    return {"cell_type": "markdown", "metadata": {}, "source": source, "id": "md"+str(abs(hash(source[:30])))}

def code(source):
    if isinstance(source, list):
        source = "".join(source)
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": source, "id": "code"+str(abs(hash(source[:30])))}

cells = []

# ─── SECTION 1 ── Environment & Data Loading ───────────────────────────────
cells.append(md(["# RACE Reading Comprehension — EDA & Training Notebook\n",
                 "**BS(CS) Spring 2026 | AL2002 Lab Project**\n\n",
                 "Run *Kernel → Restart & Run All* to execute end-to-end."]))

cells.append(md(["## Section 1 — Environment & Data Loading"]))

cells.append(code([
    "# ── Install / upgrade packages if needed (safe to re-run) ──\n",
    "import subprocess, sys\n",
    "pkgs = ['scikit-learn','gensim','xgboost','seaborn','matplotlib',\n",
    "        'joblib','pandas','numpy','pytest','kagglehub']\n",
    "subprocess.check_call([sys.executable,'-m','pip','install','--quiet',*pkgs])\n",
    "print('All packages ready.')"
]))

cells.append(code([
    "import os, re, time, warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib\n",
    "matplotlib.use('Agg')   # non-interactive backend — safe for Colab & headless\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import joblib\n",
    "from scipy.sparse import hstack, save_npz, load_npz\n",
    "from collections import Counter\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import LinearSVC\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.ensemble import RandomForestClassifier, VotingClassifier\n",
    "from sklearn.calibration import CalibratedClassifierCV\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn.mixture import GaussianMixture\n",
    "from sklearn.semi_supervised import LabelPropagation\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, f1_score, precision_score, recall_score,\n",
    "    confusion_matrix, silhouette_score, r2_score, classification_report\n",
    ")\n",
    "warnings.filterwarnings('ignore')\n",
    "np.random.seed(42)\n",
    "\n",
    "IS_KAGGLE = os.path.exists('/kaggle/working')\n",
    "BASE_DIR = '/kaggle/working/race_rc_project' if IS_KAGGLE else '..'\n",
    "RAW_DIR = os.path.join(BASE_DIR, 'data', 'raw')\n",
    "PROCESSED_DIR = os.path.join(BASE_DIR, 'data', 'processed')\n",
    "FIGURES_DIR = os.path.join(PROCESSED_DIR, 'figures')\n",
    "MODELS_A_DIR = os.path.join(BASE_DIR, 'models', 'model_a', 'traditional')\n",
    "MODELS_B_DIR = os.path.join(BASE_DIR, 'models', 'model_b', 'traditional')\n",
    "for d in [RAW_DIR, FIGURES_DIR, PROCESSED_DIR, MODELS_A_DIR, MODELS_B_DIR]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "print(f'Imports OK. Directories ready. BASE_DIR={BASE_DIR}')"
]))

cells.append(md(["### 1.1 Download dataset via kagglehub"]))

cells.append(code([
    "import kagglehub\n",
    "\n",
    "# Download RACE dataset from Kaggle\n",
    "path = kagglehub.dataset_download('ankitdhiman7/race-dataset')\n",
    "print('Path to dataset files:', path)\n",
    "\n",
    "# Locate the CSV file\n",
    "csv_candidates = []\n",
    "for root, dirs, files in os.walk(path):\n",
    "    for f in files:\n",
    "        if f.endswith('.csv'):\n",
    "            csv_candidates.append(os.path.join(root, f))\n",
    "print('Found CSVs:', csv_candidates)"
]))

cells.append(code([
    "# Load and split the dataset 80-10-10\n",
    "assert len(csv_candidates) > 0, 'No CSV found in downloaded dataset!'\n",
    "\n",
    "# Use first CSV (or the largest one)\n",
    "csv_path = sorted(csv_candidates, key=os.path.getsize)[-1]\n",
    "print(f'Using: {csv_path}')\n",
    "\n",
    "full_df = pd.read_csv(csv_path)\n",
    "print('Full dataset shape:', full_df.shape)\n",
    "print('Columns:', full_df.columns.tolist())\n",
    "print(full_df.head(2))"
]))

cells.append(code([
    "# Standardise column names (handle variations across Kaggle versions)\n",
    "col_map = {}\n",
    "for c in full_df.columns:\n",
    "    cl = c.strip().lower()\n",
    "    if cl in ('article','passage','context'): col_map[c] = 'article'\n",
    "    elif cl == 'question': col_map[c] = 'question'\n",
    "    elif cl in ('a','option_a','option a'): col_map[c] = 'A'\n",
    "    elif cl in ('b','option_b','option b'): col_map[c] = 'B'\n",
    "    elif cl in ('c','option_c','option c'): col_map[c] = 'C'\n",
    "    elif cl in ('d','option_d','option d'): col_map[c] = 'D'\n",
    "    elif cl in ('answer','label'): col_map[c] = 'answer'\n",
    "    elif cl in ('id','example_id'): col_map[c] = 'id'\n",
    "full_df.rename(columns=col_map, inplace=True)\n",
    "\n",
    "# Keep only rows with all required columns\n",
    "required = ['article','question','A','B','C','D','answer']\n",
    "missing = [c for c in required if c not in full_df.columns]\n",
    "if missing:\n",
    "    print(f'WARNING: missing columns {missing}. Available: {full_df.columns.tolist()}')\n",
    "else:\n",
    "    full_df = full_df.dropna(subset=required).reset_index(drop=True)\n",
    "    print(f'After dropna: {full_df.shape}')"
]))

cells.append(code([
    "# 80-10-10 split\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "n = len(full_df)\n",
    "train_end = int(0.8 * n)\n",
    "val_end   = int(0.9 * n)\n",
    "\n",
    "full_df = full_df.sample(frac=1, random_state=42).reset_index(drop=True)\n",
    "train_df = full_df.iloc[:train_end].reset_index(drop=True)\n",
    "val_df   = full_df.iloc[train_end:val_end].reset_index(drop=True)\n",
    "test_df  = full_df.iloc[val_end:].reset_index(drop=True)\n",
    "\n",
    "print(f'Train: {train_df.shape}, Val: {val_df.shape}, Test: {test_df.shape}')\n",
    "\n",
    "# Save raw splits for reference\n",
    "train_df.to_csv(os.path.join(RAW_DIR, 'train.csv'), index=False)\n",
    "val_df.to_csv(os.path.join(RAW_DIR, 'val.csv'),   index=False)\n",
    "test_df.to_csv(os.path.join(RAW_DIR, 'test.csv'), index=False)\n",
    "print(f'Splits saved to: {RAW_DIR}')"
]))

cells.append(code([
    "# Sanity checks\n",
    "for split_name, df in [('train', train_df), ('val', val_df), ('test', test_df)]:\n",
    "    assert all(c in df.columns for c in required), f'{split_name} missing columns'\n",
    "    assert df[required].isnull().sum().sum() == 0, f'{split_name} has nulls'\n",
    "    assert df['answer'].isin(['A','B','C','D']).all(), f'{split_name} has invalid answers'\n",
    "    print(f'{split_name}: {len(df)} rows — OK')"
]))

# ─── SECTION 2 ── EDA ──────────────────────────────────────────────────────
cells.append(md(["## Section 2 — Exploratory Data Analysis"]))

cells.append(code([
    "# ── 2.1 Answer label distribution ──\n",
    "fig, ax = plt.subplots(figsize=(6,4))\n",
    "counts = train_df['answer'].value_counts().sort_index()\n",
    "ax.bar(counts.index, counts.values, color=['#4C72B0','#DD8452','#55A868','#C44E52'])\n",
    "ax.set_title('Answer Label Distribution (Train Set)')\n",
    "ax.set_xlabel('Answer Option')\n",
    "ax.set_ylabel('Count')\n",
    "for i,(lbl,cnt) in enumerate(zip(counts.index, counts.values)):\n",
    "    ax.text(i, cnt+50, str(cnt), ha='center', fontsize=9)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/01_answer_distribution.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 01_answer_distribution.png')"
]))

cells.append(code([
    "# ── 2.2 Article length distribution ──\n",
    "train_df['article_len'] = train_df['article'].str.split().str.len()\n",
    "fig, ax = plt.subplots(figsize=(8,4))\n",
    "ax.hist(train_df['article_len'], bins=50, color='steelblue', edgecolor='white')\n",
    "ax.set_title('Article Length Distribution (word count)')\n",
    "ax.set_xlabel('Words')\n",
    "ax.set_ylabel('Frequency')\n",
    "ax.axvline(train_df['article_len'].mean(), color='red', linestyle='--', label=f'Mean={train_df[\"article_len\"].mean():.0f}')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/02_article_length.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 02_article_length.png')"
]))

cells.append(code([
    "# ── 2.3 Question length distribution ──\n",
    "train_df['q_len'] = train_df['question'].str.split().str.len()\n",
    "fig, ax = plt.subplots(figsize=(8,4))\n",
    "ax.hist(train_df['q_len'], bins=30, color='darkorange', edgecolor='white')\n",
    "ax.set_title('Question Length Distribution (word count)')\n",
    "ax.set_xlabel('Words')\n",
    "ax.set_ylabel('Frequency')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/03_question_length.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 03_question_length.png')"
]))

cells.append(code([
    "# ── 2.4 Option length distribution (avg per option vs correct option) ──\n",
    "for opt in ['A','B','C','D']:\n",
    "    train_df[f'{opt}_len'] = train_df[opt].str.split().str.len()\n",
    "\n",
    "avg_all = {opt: train_df[f'{opt}_len'].mean() for opt in ['A','B','C','D']}\n",
    "correct_mask = {opt: train_df['answer']==opt for opt in ['A','B','C','D']}\n",
    "avg_correct = {opt: train_df.loc[correct_mask[opt], f'{opt}_len'].mean() for opt in ['A','B','C','D']}\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8,5))\n",
    "x = np.arange(4)\n",
    "w = 0.35\n",
    "ax.bar(x - w/2, [avg_all[o] for o in 'ABCD'],   w, label='All options', color='steelblue')\n",
    "ax.bar(x + w/2, [avg_correct[o] for o in 'ABCD'], w, label='Correct option', color='darkorange')\n",
    "ax.set_xticks(x); ax.set_xticklabels(list('ABCD'))\n",
    "ax.set_title('Average Option Length — All vs Correct')\n",
    "ax.set_xlabel('Option'); ax.set_ylabel('Avg Word Count')\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/04_option_length.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 04_option_length.png')"
]))

cells.append(code([
    "# ── 2.5 Question type breakdown (first word) ──\n",
    "wh_words = ['who','what','where','when','why','how','which','whose']\n",
    "def qtype(q):\n",
    "    first = str(q).lower().split()[0].strip('\\\"\\'')\n",
    "    return first if first in wh_words else 'fill-in / other'\n",
    "\n",
    "train_df['q_type'] = train_df['question'].apply(qtype)\n",
    "qtc = train_df['q_type'].value_counts()\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8,5))\n",
    "ax.barh(qtc.index[::-1], qtc.values[::-1], color='mediumseagreen')\n",
    "ax.set_title('Question Type Breakdown (First Word)')\n",
    "ax.set_xlabel('Count')\n",
    "for i,(idx,v) in enumerate(zip(qtc.index[::-1], qtc.values[::-1])):\n",
    "    ax.text(v+10, i, str(v), va='center', fontsize=9)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/05_question_types.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 05_question_types.png')"
]))

cells.append(code([
    "# ── 2.6 Middle vs High school split (from 'id' or difficulty column if present) ──\n",
    "if 'id' in train_df.columns:\n",
    "    train_df['difficulty'] = train_df['id'].astype(str).apply(\n",
    "        lambda x: 'high' if 'high' in x.lower() else ('middle' if 'middle' in x.lower() else 'unknown')\n",
    "    )\n",
    "elif 'difficulty' not in train_df.columns:\n",
    "    # Assign based on article length as proxy (shorter = middle school)\n",
    "    med = train_df['article_len'].median()\n",
    "    train_df['difficulty'] = train_df['article_len'].apply(lambda x: 'high' if x>=med else 'middle')\n",
    "\n",
    "diff_counts = train_df['difficulty'].value_counts()\n",
    "fig, ax = plt.subplots(figsize=(5,5))\n",
    "ax.pie(diff_counts.values, labels=diff_counts.index, autopct='%1.1f%%',\n",
    "       colors=['#4C72B0','#DD8452','#aec7e8'], startangle=140)\n",
    "ax.set_title('Middle vs High School Split (Train)')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/06_difficulty_split.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 06_difficulty_split.png')"
]))

cells.append(code([
    "# ── 2.7 Answer label balance across splits ──\n",
    "splits = {'train': train_df, 'val': val_df, 'test': test_df}\n",
    "fig, axes = plt.subplots(1,3, figsize=(12,4), sharey=True)\n",
    "for ax, (name, df) in zip(axes, splits.items()):\n",
    "    c = df['answer'].value_counts().sort_index()\n",
    "    ax.bar(c.index, c.values, color=['#4C72B0','#DD8452','#55A868','#C44E52'])\n",
    "    ax.set_title(f'{name.capitalize()} ({len(df)} rows)')\n",
    "    ax.set_xlabel('Answer')\n",
    "    ax.set_ylabel('Count')\n",
    "plt.suptitle('Answer Label Distribution by Split', fontsize=13)\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/07_answer_by_split.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 07_answer_by_split.png')"
]))

cells.append(code([
    "# ── 2.8 Summary statistics ──\n",
    "all_tokens = ' '.join(train_df['article'].fillna('').tolist()).split()\n",
    "vocab_size = len(set(all_tokens))\n",
    "print('\\n=== DATASET SUMMARY STATISTICS ===')\n",
    "print(f\"{'Metric':<35} {'Value'}\")\n",
    "print('-'*55)\n",
    "print(f\"{'Total questions (full)':<35} {len(full_df):,}\")\n",
    "print(f\"{'Train / Val / Test':<35} {len(train_df):,} / {len(val_df):,} / {len(test_df):,}\")\n",
    "print(f\"{'Mean article length (words)':<35} {train_df['article_len'].mean():.1f}\")\n",
    "print(f\"{'Median article length (words)':<35} {train_df['article_len'].median():.1f}\")\n",
    "print(f\"{'Max article length (words)':<35} {train_df['article_len'].max()}\")\n",
    "print(f\"{'Mean question length (words)':<35} {train_df['q_len'].mean():.1f}\")\n",
    "print(f\"{'Train vocab size (unique tokens)':<35} {vocab_size:,}\")\n",
    "print(f\"{'Answer A %':<35} {(train_df['answer']=='A').mean()*100:.1f}%\")\n",
    "print(f\"{'Answer B %':<35} {(train_df['answer']=='B').mean()*100:.1f}%\")\n",
    "print(f\"{'Answer C %':<35} {(train_df['answer']=='C').mean()*100:.1f}%\")\n",
    "print(f\"{'Answer D %':<35} {(train_df['answer']=='D').mean()*100:.1f}%\")"
]))

# ─── SECTION 3 ── Preprocessing ────────────────────────────────────────────
cells.append(md(["## Section 3 — Preprocessing Pipeline"]))

cells.append(code([
    "# ── 3.1 Text cleaning ──\n",
    "import string\n",
    "\n",
    "def clean_text(text):\n",
    "    \"\"\"Lowercase, remove punctuation, strip extra whitespace.\"\"\"\n",
    "    text = str(text).lower()\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    text = re.sub(r'\\s+', ' ', text).strip()\n",
    "    return text\n",
    "\n",
    "# Apply to all text columns\n",
    "for df in [train_df, val_df, test_df]:\n",
    "    df['article_clean']  = df['article'].apply(clean_text)\n",
    "    df['question_clean'] = df['question'].apply(clean_text)\n",
    "    for opt in ['A','B','C','D']:\n",
    "        df[f'{opt}_clean'] = df[opt].apply(clean_text)\n",
    "\n",
    "print('Text cleaning done.')\n",
    "print('Example cleaned article:', train_df['article_clean'].iloc[0][:120])"
]))

cells.append(code([
    "# ── 3.2 Data expansion: 1 row per option ──\n",
    "def expand_df(df):\n",
    "    rows = []\n",
    "    for _, r in df.iterrows():\n",
    "        for opt in ['A','B','C','D']:\n",
    "            rows.append({\n",
    "                'article'       : r['article_clean'],\n",
    "                'question'      : r['question_clean'],\n",
    "                'option'        : r[f'{opt}_clean'],\n",
    "                'option_letter' : opt,\n",
    "                'label'         : 1 if r['answer'] == opt else 0,\n",
    "                'combined_text' : r['article_clean'] + ' [SEP] ' + r['question_clean'] + ' [SEP] ' + r[f'{opt}_clean'],\n",
    "                'article_raw'   : r['article'],\n",
    "                'question_raw'  : r['question'],\n",
    "                'A_raw': r['A'], 'B_raw': r['B'], 'C_raw': r['C'], 'D_raw': r['D'],\n",
    "                'answer'        : r['answer'],\n",
    "            })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "print('Expanding datasets (1 row per option)...')\n",
    "train_exp = expand_df(train_df)\n",
    "val_exp   = expand_df(val_df)\n",
    "test_exp  = expand_df(test_df)\n",
    "print(f'Expanded → Train: {train_exp.shape}, Val: {val_exp.shape}, Test: {test_exp.shape}')\n",
    "print(train_exp[['option_letter','label','combined_text']].head(4))"
]))

cells.append(code([
    "# ── 3.3 One-Hot Encoding (CountVectorizer binary=True) ──\n",
    "print('Building One-Hot vocabulary (top 5000 tokens)...')\n",
    "ohe_vec = CountVectorizer(binary=True, max_features=5000, min_df=2)\n",
    "X_ohe_train = ohe_vec.fit_transform(train_exp['combined_text'])\n",
    "X_ohe_val   = ohe_vec.transform(val_exp['combined_text'])\n",
    "X_ohe_test  = ohe_vec.transform(test_exp['combined_text'])\n",
    "print(f'OHE feature matrix shapes: train={X_ohe_train.shape}, val={X_ohe_val.shape}, test={X_ohe_test.shape}')\n",
    "joblib.dump(ohe_vec, f'{MODELS_A_DIR}/ohe_vectorizer.pkl')\n",
    "print('OHE vectorizer saved.')"
]))

cells.append(code([
    "# ── 3.4 Cosine similarity feature (article vs option) ──\n",
    "from sklearn.metrics.pairwise import cosine_similarity as cos_sim\n",
    "from scipy.sparse import csr_matrix\n",
    "\n",
    "print('Computing cosine similarity features...')\n",
    "art_vec = CountVectorizer(binary=True, max_features=5000, vocabulary=ohe_vec.vocabulary_)\n",
    "\n",
    "def cos_feature(df_exp):\n",
    "    art_mat = art_vec.transform(df_exp['article'])\n",
    "    opt_mat = art_vec.transform(df_exp['option'])\n",
    "    # Row-wise cosine similarity\n",
    "    scores = np.array([\n",
    "        cos_sim(art_mat[i], opt_mat[i])[0,0]\n",
    "        for i in range(art_mat.shape[0])\n",
    "    ]).reshape(-1,1)\n",
    "    return csr_matrix(scores)\n",
    "\n",
    "cos_train = cos_feature(train_exp)\n",
    "cos_val   = cos_feature(val_exp)\n",
    "cos_test  = cos_feature(test_exp)\n",
    "print('Cosine features computed.')"
]))

cells.append(code([
    "# ── 3.5 Lexical features ──\n",
    "def lexical_features(df_exp):\n",
    "    feats = []\n",
    "    for _, r in df_exp.iterrows():\n",
    "        art_toks = set(r['article'].split())\n",
    "        q_toks   = set(r['question'].split())\n",
    "        opt_toks = set(r['option'].split())\n",
    "        opt_list = r['option'].split()\n",
    "        art_str  = r['article']\n",
    "\n",
    "        option_length    = len(opt_list)\n",
    "        question_length  = len(r['question'].split())\n",
    "        keyword_overlap  = len(q_toks & opt_toks)\n",
    "        opt_in_article   = len(opt_toks & art_toks)\n",
    "        # position of first option token in article (normalised)\n",
    "        pos = 0.0\n",
    "        if opt_list and opt_list[0] in art_str:\n",
    "            idx = art_str.find(opt_list[0])\n",
    "            pos = idx / max(len(art_str), 1)\n",
    "        feats.append([option_length, question_length, keyword_overlap, opt_in_article, pos])\n",
    "    return csr_matrix(np.array(feats, dtype=np.float32))\n",
    "\n",
    "print('Computing lexical features (this may take a minute)...')\n",
    "lex_train = lexical_features(train_exp)\n",
    "lex_val   = lexical_features(val_exp)\n",
    "lex_test  = lexical_features(test_exp)\n",
    "print('Lexical features computed.')"
]))

cells.append(code([
    "# ── 3.6 Final feature matrix: hstack OHE + cosine + lexical ──\n",
    "X_train = hstack([X_ohe_train, cos_train, lex_train])\n",
    "X_val   = hstack([X_ohe_val,   cos_val,   lex_val])\n",
    "X_test  = hstack([X_ohe_test,  cos_test,  lex_test])\n",
    "\n",
    "y_train = train_exp['label'].values\n",
    "y_val   = val_exp['label'].values\n",
    "y_test  = test_exp['label'].values\n",
    "\n",
    "print(f'Final feature shapes: train={X_train.shape}, val={X_val.shape}, test={X_test.shape}')\n",
    "print(f'Label distributions — train: {Counter(y_train)}, val: {Counter(y_val)}, test: {Counter(y_test)}')\n",
    "\n",
    "# Save feature matrices\n",
    "save_npz(f'{PROCESSED_DIR}/X_train.npz', X_train)\n",
    "save_npz(f'{PROCESSED_DIR}/X_val.npz',   X_val)\n",
    "save_npz(f'{PROCESSED_DIR}/X_test.npz',  X_test)\n",
    "np.save(f'{PROCESSED_DIR}/y_train.npy', y_train)\n",
    "np.save(f'{PROCESSED_DIR}/y_val.npy',   y_val)\n",
    "np.save(f'{PROCESSED_DIR}/y_test.npy',  y_test)\n",
    "\n",
    "# Also save expanded dataframes for Model B and inference\n",
    "train_exp.to_csv(f'{PROCESSED_DIR}/train_exp.csv', index=False)\n",
    "val_exp.to_csv(f'{PROCESSED_DIR}/val_exp.csv',     index=False)\n",
    "test_exp.to_csv(f'{PROCESSED_DIR}/test_exp.csv',   index=False)\n",
    "print('Feature matrices and expanded dataframes saved.')"
]))

cells.append(code([
    "%%writefile ../src/preprocessing.py\n",
    "\"\"\"preprocessing.py — RACE dataset loading and feature engineering.\"\"\"\n",
    "import os, re, string\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import joblib\n",
    "from scipy.sparse import hstack, load_npz, csr_matrix\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity as cos_sim\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    text = str(text).lower()\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    return re.sub(r'\\s+', ' ', text).strip()\n",
    "\n",
    "\n",
    "def expand_df(df):\n",
    "    rows = []\n",
    "    for _, r in df.iterrows():\n",
    "        for opt in ['A','B','C','D']:\n",
    "            a_c = clean_text(r['article'])\n",
    "            q_c = clean_text(r['question'])\n",
    "            o_c = clean_text(r[opt])\n",
    "            rows.append({\n",
    "                'article': a_c, 'question': q_c, 'option': o_c,\n",
    "                'option_letter': opt,\n",
    "                'label': 1 if r['answer'] == opt else 0,\n",
    "                'combined_text': f'{a_c} [SEP] {q_c} [SEP] {o_c}',\n",
    "                'article_raw': r['article'], 'question_raw': r['question'],\n",
    "                'A_raw': r['A'], 'B_raw': r['B'], 'C_raw': r['C'], 'D_raw': r['D'],\n",
    "                'answer': r['answer'],\n",
    "            })\n",
    "    return pd.DataFrame(rows)\n",
    "\n",
    "\n",
    "def build_features(train_exp, val_exp, test_exp, save_dir='data/processed',\n",
    "                   models_dir='models/model_a/traditional', max_features=5000):\n",
    "    os.makedirs(save_dir, exist_ok=True)\n",
    "    ohe_vec = CountVectorizer(binary=True, max_features=max_features, min_df=2)\n",
    "    X_ohe_tr = ohe_vec.fit_transform(train_exp['combined_text'])\n",
    "    X_ohe_va = ohe_vec.transform(val_exp['combined_text'])\n",
    "    X_ohe_te = ohe_vec.transform(test_exp['combined_text'])\n",
    "    joblib.dump(ohe_vec, os.path.join(models_dir, 'ohe_vectorizer.pkl'))\n",
    "\n",
    "    art_vec = CountVectorizer(binary=True, vocabulary=ohe_vec.vocabulary_)\n",
    "    def cos_feature(df_e):\n",
    "        am = art_vec.transform(df_e['article'])\n",
    "        om = art_vec.transform(df_e['option'])\n",
    "        scores = np.array([cos_sim(am[i], om[i])[0,0] for i in range(am.shape[0])]).reshape(-1,1)\n",
    "        return csr_matrix(scores)\n",
    "    def lex_feat(df_e):\n",
    "        feats = []\n",
    "        for _, r in df_e.iterrows():\n",
    "            at = set(r['article'].split()); qt = set(r['question'].split()); ot = set(r['option'].split())\n",
    "            ol = list(r['option'].split()); art_s = r['article']\n",
    "            pos = 0.0\n",
    "            if ol and ol[0] in art_s: pos = art_s.find(ol[0]) / max(len(art_s),1)\n",
    "            feats.append([len(ol), len(r['question'].split()), len(qt&ot), len(ot&at), pos])\n",
    "        return csr_matrix(np.array(feats, dtype=np.float32))\n",
    "\n",
    "    from scipy.sparse import save_npz\n",
    "    for name, df_e, X_ohe in [('train',train_exp,X_ohe_tr),('val',val_exp,X_ohe_va),('test',test_exp,X_ohe_te)]:\n",
    "        X = hstack([X_ohe, cos_feature(df_e), lex_feat(df_e)])\n",
    "        save_npz(os.path.join(save_dir, f'X_{name}.npz'), X)\n",
    "        np.save(os.path.join(save_dir, f'y_{name}.npy'), df_e['label'].values)\n",
    "    return ohe_vec\n",
    "\n",
    "\n",
    "def load_features(processed_dir='data/processed'):\n",
    "    X_tr = load_npz(os.path.join(processed_dir, 'X_train.npz'))\n",
    "    X_va = load_npz(os.path.join(processed_dir, 'X_val.npz'))\n",
    "    X_te = load_npz(os.path.join(processed_dir, 'X_test.npz'))\n",
    "    y_tr = np.load(os.path.join(processed_dir, 'y_train.npy'))\n",
    "    y_va = np.load(os.path.join(processed_dir, 'y_val.npy'))\n",
    "    y_te = np.load(os.path.join(processed_dir, 'y_test.npy'))\n",
    "    return X_tr, X_va, X_te, y_tr, y_va, y_te\n"
]))

# ─── SECTION 4 ── Model A Traditional ML ───────────────────────────────────
cells.append(md(["## Section 4 — Model A: Traditional ML (Answer Verification)"]))

cells.append(md(["### 4a. Logistic Regression\nSuperclassifier over full OHE + cosine + lexical features. Strong baseline for text classification."]))

cells.append(code([
    "# ── Helper: Exact Match accuracy for MC (4-way) ──\n",
    "def exact_match(y_true_exp, y_pred_exp, n_options=4):\n",
    "    \"\"\"Fraction of questions where argmax predicted score == correct option.\"\"\"\n",
    "    n = len(y_true_exp) // n_options\n",
    "    correct = 0\n",
    "    for i in range(n):\n",
    "        block = y_pred_exp[i*n_options:(i+1)*n_options]\n",
    "        true_block = y_true_exp[i*n_options:(i+1)*n_options]\n",
    "        if true_block.sum() == 0: continue\n",
    "        if np.argmax(block) == np.argmax(true_block):\n",
    "            correct += 1\n",
    "    return correct / max(n, 1)\n",
    "\n",
    "results = {}  # store results for comparison table\n",
    "print('Helper defined.')"
]))

cells.append(code([
    "t0 = time.time()\n",
    "lr_model = LogisticRegression(max_iter=1000, C=1.0, solver='saga', n_jobs=-1)\n",
    "lr_model.fit(X_train, y_train)\n",
    "train_time_lr = time.time() - t0\n",
    "\n",
    "lr_val_pred  = lr_model.predict(X_val)\n",
    "lr_val_proba = lr_model.predict_proba(X_val)[:,1]\n",
    "\n",
    "lr_acc = accuracy_score(y_val, lr_val_pred)\n",
    "lr_f1  = f1_score(y_val, lr_val_pred, average='macro')\n",
    "lr_em  = exact_match(y_val, lr_val_proba)\n",
    "\n",
    "print(f'Logistic Regression — Val Accuracy: {lr_acc:.4f}, Macro F1: {lr_f1:.4f}, EM: {lr_em:.4f}')\n",
    "print(f'Train time: {train_time_lr:.1f}s')\n",
    "results['Logistic Regression'] = {'accuracy': lr_acc, 'f1': lr_f1, 'em': lr_em, 'time': train_time_lr}\n",
    "\n",
    "joblib.dump(lr_model, f'{MODELS_A_DIR}/lr_model.pkl')\n",
    "print('LR model saved.')"
]))

cells.append(md(["### 4b. Support Vector Machine (LinearSVC + Calibration)"]))

cells.append(code([
    "t0 = time.time()\n",
    "svm_base  = LinearSVC(max_iter=2000, C=1.0)\n",
    "svm_model = CalibratedClassifierCV(svm_base, cv=3)\n",
    "svm_model.fit(X_train, y_train)\n",
    "train_time_svm = time.time() - t0\n",
    "\n",
    "svm_val_pred  = svm_model.predict(X_val)\n",
    "svm_val_proba = svm_model.predict_proba(X_val)[:,1]\n",
    "\n",
    "svm_acc = accuracy_score(y_val, svm_val_pred)\n",
    "svm_f1  = f1_score(y_val, svm_val_pred, average='macro')\n",
    "svm_em  = exact_match(y_val, svm_val_proba)\n",
    "\n",
    "print(f'SVM (Calibrated) — Val Accuracy: {svm_acc:.4f}, Macro F1: {svm_f1:.4f}, EM: {svm_em:.4f}')\n",
    "print(f'Train time: {train_time_svm:.1f}s')\n",
    "results['SVM (Calibrated)'] = {'accuracy': svm_acc, 'f1': svm_f1, 'em': svm_em, 'time': train_time_svm}\n",
    "\n",
    "joblib.dump(svm_model, f'{MODELS_A_DIR}/svm_model.pkl')\n",
    "print('SVM model saved.')"
]))

cells.append(md(["### 4c. Naive Bayes — Question Type Classifier\nUsed to classify questions by type (Who/What/Where/…), a useful auxiliary task."]))

cells.append(code([
    "# Prepare question-type classification data\n",
    "q_vec = CountVectorizer(max_features=3000)\n",
    "X_qtrain = q_vec.fit_transform(train_df['question_clean'])\n",
    "X_qval   = q_vec.transform(val_df['question_clean'])\n",
    "\n",
    "y_qtrain = train_df['q_type'].values\n",
    "y_qval   = val_df['q_type'].apply(qtype).values if 'q_type' not in val_df.columns else val_df['q_type'].values\n",
    "\n",
    "t0 = time.time()\n",
    "nb_model = MultinomialNB()\n",
    "nb_model.fit(X_qtrain, y_qtrain)\n",
    "train_time_nb = time.time() - t0\n",
    "\n",
    "nb_pred = nb_model.predict(X_qval)\n",
    "nb_acc  = accuracy_score(y_qval, nb_pred)\n",
    "nb_f1   = f1_score(y_qval, nb_pred, average='macro', zero_division=0)\n",
    "\n",
    "print(f'Naive Bayes (Q-type) — Val Accuracy: {nb_acc:.4f}, Macro F1: {nb_f1:.4f}')\n",
    "print(f'Train time: {train_time_nb:.1f}s')\n",
    "results['Naive Bayes (Q-type)'] = {'accuracy': nb_acc, 'f1': nb_f1, 'em': 'N/A', 'time': train_time_nb}\n",
    "\n",
    "joblib.dump(nb_model, f'{MODELS_A_DIR}/nb_model.pkl')\n",
    "joblib.dump(q_vec,    f'{MODELS_A_DIR}/nb_vectorizer.pkl')\n",
    "print('NB model saved.')"
]))

cells.append(md(["### 4d. Random Forest — Lexical Features Only"]))

cells.append(code([
    "# Extract lexical-only features (dense, suitable for RF)\n",
    "# lexical: cols are [option_length, question_length, keyword_overlap, opt_in_article, answer_position]\n",
    "lex_start = X_ohe_train.shape[1] + 1  # after OHE + cosine col\n",
    "X_lex_train = np.asarray(lex_train.todense())\n",
    "X_lex_val   = np.asarray(lex_val.todense())\n",
    "X_lex_test  = np.asarray(lex_test.todense())\n",
    "\n",
    "t0 = time.time()\n",
    "rf_model = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)\n",
    "rf_model.fit(X_lex_train, y_train)\n",
    "train_time_rf = time.time() - t0\n",
    "\n",
    "rf_val_pred  = rf_model.predict(X_lex_val)\n",
    "rf_val_proba = rf_model.predict_proba(X_lex_val)[:,1]\n",
    "\n",
    "rf_acc = accuracy_score(y_val, rf_val_pred)\n",
    "rf_f1  = f1_score(y_val, rf_val_pred, average='macro')\n",
    "rf_em  = exact_match(y_val, rf_val_proba)\n",
    "\n",
    "print(f'Random Forest — Val Accuracy: {rf_acc:.4f}, Macro F1: {rf_f1:.4f}, EM: {rf_em:.4f}')\n",
    "print(f'Train time: {train_time_rf:.1f}s')\n",
    "results['Random Forest'] = {'accuracy': rf_acc, 'f1': rf_f1, 'em': rf_em, 'time': train_time_rf}\n",
    "\n",
    "joblib.dump(rf_model, f'{MODELS_A_DIR}/rf_model.pkl')\n",
    "print('RF model saved.')"
]))

cells.append(code([
    "# ── 4e. Model A comparison table ──\n",
    "print(f\"{'Model':<25} | {'Accuracy':>8} | {'Macro F1':>8} | {'Exact Match':>11} | {'Train time':>10}\")\n",
    "print('-'*75)\n",
    "for model_name, m in results.items():\n",
    "    em_str = f\"{m['em']:.4f}\" if isinstance(m['em'], float) else m['em']\n",
    "    print(f\"{model_name:<25} | {m['accuracy']:>8.4f} | {m['f1']:>8.4f} | {em_str:>11} | {m['time']:>8.1f}s\")"
]))

# ─── SECTION 5 ── Unsupervised & Semi-Supervised ──────────────────────────
cells.append(md(["## Section 5 — Model A: Unsupervised & Semi-Supervised"]))

cells.append(md(["### 5a. K-Means Clustering with Elbow Method"]))

cells.append(code([
    "# Work on a sample (K-Means on full sparse matrix is slow)\n",
    "SAMPLE = min(10000, X_train.shape[0])\n",
    "idx = np.random.choice(X_train.shape[0], SAMPLE, replace=False)\n",
    "X_sample = X_train[idx].toarray()\n",
    "y_sample = y_train[idx]\n",
    "\n",
    "# Elbow method\n",
    "inertias = []\n",
    "K_range = range(2, 11)\n",
    "for k in K_range:\n",
    "    km = KMeans(n_clusters=k, random_state=42, n_init=5, max_iter=100)\n",
    "    km.fit(X_sample)\n",
    "    inertias.append(km.inertia_)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(7,4))\n",
    "ax.plot(list(K_range), inertias, 'o-', color='steelblue')\n",
    "ax.set_title('K-Means Elbow Curve')\n",
    "ax.set_xlabel('Number of Clusters (K)')\n",
    "ax.set_ylabel('Inertia')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/08_kmeans_elbow.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 08_kmeans_elbow.png')"
]))

cells.append(code([
    "# Fit final K-Means (K=2 is natural: correct/incorrect)\n",
    "BEST_K = 2\n",
    "km_final = KMeans(n_clusters=BEST_K, random_state=42, n_init=10, max_iter=200)\n",
    "km_labels = km_final.fit_predict(X_sample)\n",
    "\n",
    "# Silhouette score (subsample for speed)\n",
    "sil_idx = np.random.choice(len(km_labels), min(2000, len(km_labels)), replace=False)\n",
    "sil_score = silhouette_score(X_sample[sil_idx], km_labels[sil_idx])\n",
    "\n",
    "# Clustering purity\n",
    "def purity_score(y_true, y_pred):\n",
    "    from scipy.stats import mode\n",
    "    total = 0\n",
    "    for cluster in np.unique(y_pred):\n",
    "        mask = y_pred == cluster\n",
    "        majority = mode(y_true[mask], keepdims=True).count[0]\n",
    "        total += majority\n",
    "    return total / len(y_true)\n",
    "\n",
    "purity = purity_score(y_sample, km_labels)\n",
    "print(f'K-Means (K={BEST_K}) — Silhouette Score: {sil_score:.4f}, Purity: {purity:.4f}')\n",
    "\n",
    "# PCA 2D visualization\n",
    "pca = PCA(n_components=2, random_state=42)\n",
    "X_2d = pca.fit_transform(X_sample[:2000])\n",
    "fig, ax = plt.subplots(figsize=(7,5))\n",
    "for c, label in [(0,'Cluster 0'),(1,'Cluster 1')]:\n",
    "    mask = km_labels[:2000] == c\n",
    "    ax.scatter(X_2d[mask,0], X_2d[mask,1], s=5, alpha=0.5, label=label)\n",
    "ax.set_title('K-Means Clusters (PCA 2D)')\n",
    "ax.set_xlabel('PC1'); ax.set_ylabel('PC2'); ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/09_kmeans_pca.png', dpi=100)\n",
    "plt.show()\n",
    "print('Saved 09_kmeans_pca.png')"
]))

cells.append(md(["### 5b. Gaussian Mixture Model"]))

cells.append(code([
    "gmm = GaussianMixture(n_components=BEST_K, random_state=42, covariance_type='diag')\n",
    "gmm.fit(X_sample)\n",
    "gmm_labels_hard = gmm.predict(X_sample)\n",
    "gmm_labels_soft  = gmm.predict_proba(X_sample)\n",
    "\n",
    "sil_gmm = silhouette_score(X_sample[sil_idx], gmm_labels_hard[sil_idx])\n",
    "log_lik = gmm.score(X_sample)\n",
    "purity_gmm = purity_score(y_sample, gmm_labels_hard)\n",
    "\n",
    "print(f'GMM — Silhouette: {sil_gmm:.4f}, Log-Likelihood: {log_lik:.4f}, Purity: {purity_gmm:.4f}')\n",
    "\n",
    "print('\\n--- Hard vs Soft Assignment Comparison (first 5 rows) ---')\n",
    "for i in range(5):\n",
    "    print(f'  Hard: {gmm_labels_hard[i]}  |  Soft: [{gmm_labels_soft[i,0]:.3f}, {gmm_labels_soft[i,1]:.3f}]  |  True: {y_sample[i]}')"
]))

cells.append(md(["### 5c. Label Propagation (Semi-Supervised)"]))

cells.append(code([
    "# Use 10% as labeled, rest as unlabeled (label=-1)\n",
    "SS_SAMPLE = min(5000, X_sample.shape[0])\n",
    "X_ss = X_sample[:SS_SAMPLE]\n",
    "y_ss = y_sample[:SS_SAMPLE].copy()\n",
    "\n",
    "labeled_idx = np.random.choice(SS_SAMPLE, int(0.1*SS_SAMPLE), replace=False)\n",
    "y_ss_partial = np.full(SS_SAMPLE, -1)\n",
    "y_ss_partial[labeled_idx] = y_ss[labeled_idx]\n",
    "\n",
    "lp_model = LabelPropagation(kernel='knn', n_neighbors=7, max_iter=200)\n",
    "lp_model.fit(X_ss, y_ss_partial)\n",
    "lp_preds = lp_model.predict(X_ss)\n",
    "\n",
    "# Evaluate only on unlabeled portion\n",
    "unlabeled_idx = np.where(y_ss_partial == -1)[0]\n",
    "lp_f1 = f1_score(y_ss[unlabeled_idx], lp_preds[unlabeled_idx], average='macro', zero_division=0)\n",
    "print(f'Label Propagation — Unlabeled F1: {lp_f1:.4f}')\n",
    "\n",
    "# Compare supervised LR F1 vs LP F1\n",
    "lr_sample_f1 = f1_score(y_ss, lr_model.predict(csr_matrix(X_ss)), average='macro', zero_division=0)\n",
    "print(f'\\nComparison on same {SS_SAMPLE} samples:')\n",
    "print(f\"  Supervised LR Macro F1:    {lr_sample_f1:.4f}\")\n",
    "print(f\"  Label Propagation Macro F1: {lp_f1:.4f} (unlabeled only)\")"
]))

cells.append(md(["### 5d. Ensemble — Soft Voting (LR + SVM + RF)"]))

cells.append(code([
    "# Soft voting: average predicted probabilities from LR, SVM (calibrated), RF\n",
    "# RF uses lexical features only — align it with the full val set\n",
    "print('Computing ensemble predictions on validation set...')\n",
    "\n",
    "lr_proba_val  = lr_model.predict_proba(X_val)[:,1]\n",
    "svm_proba_val = svm_model.predict_proba(X_val)[:,1]\n",
    "rf_proba_val  = rf_model.predict_proba(X_lex_val)[:,1]\n",
    "\n",
    "ens_proba_val = (lr_proba_val + svm_proba_val + rf_proba_val) / 3\n",
    "ens_pred_val  = (ens_proba_val >= 0.5).astype(int)\n",
    "\n",
    "ens_acc = accuracy_score(y_val, ens_pred_val)\n",
    "ens_f1  = f1_score(y_val, ens_pred_val, average='macro')\n",
    "ens_em  = exact_match(y_val, ens_proba_val)\n",
    "\n",
    "print(f'Ensemble (Soft Vote) — Val Accuracy: {ens_acc:.4f}, Macro F1: {ens_f1:.4f}, EM: {ens_em:.4f}')\n",
    "results['Ensemble (Soft Vote)'] = {'accuracy': ens_acc, 'f1': ens_f1, 'em': ens_em, 'time': 0}\n",
    "\n",
    "np.save(f'{PROCESSED_DIR}/ensemble_val_preds.npy', ens_proba_val)\n",
    "print('Ensemble val predictions saved.')"
]))

# ─── SECTION 6 ── Template-Based Question Generation ─────────────────────
cells.append(md(["## Section 6 — Model A: Template-Based Question Generation"]))

cells.append(code([
    "# ── 6a. Candidate sentence extraction by keyword overlap ──\n",
    "def score_sentences(article, answer, top_k=3):\n",
    "    sentences = [s.strip() for s in re.split(r'[.!?]', article) if len(s.strip()) > 10]\n",
    "    ans_toks = set(clean_text(answer).split())\n",
    "    scored = []\n",
    "    for s in sentences:\n",
    "        s_toks = set(clean_text(s).split())\n",
    "        overlap = len(s_toks & ans_toks) / max(len(ans_toks), 1)\n",
    "        scored.append((overlap, s))\n",
    "    scored.sort(reverse=True)\n",
    "    return [s for _, s in scored[:top_k]]\n",
    "\n",
    "# Test\n",
    "sample_row = train_df.iloc[0]\n",
    "cands = score_sentences(sample_row['article'], sample_row[sample_row['answer']])\n",
    "print('Top-3 candidate sentences:')\n",
    "for i, c in enumerate(cands, 1):\n",
    "    print(f'  {i}. {c[:120]}')"
]))

cells.append(code([
    "# ── 6b. Wh-word template application ──\n",
    "WH_TEMPLATES = [\n",
    "    (r'^(\\w+)\\s+(.+)',          'What did {} do?'),\n",
    "    (r'[A-Z][a-z]+(?:\\s[A-Z][a-z]+)*', 'Who is ___?'),\n",
    "]\n",
    "\n",
    "def generate_question(sentence, answer):\n",
    "    candidates = []\n",
    "    # Fill-in-the-blank template\n",
    "    ans_clean = clean_text(answer)\n",
    "    if ans_clean in clean_text(sentence):\n",
    "        blanked = re.sub(re.escape(ans_clean), '___', clean_text(sentence), count=1)\n",
    "        candidates.append(f'Fill in the blank: \"{blanked}\"')\n",
    "    # Capitalized token → Who template\n",
    "    caps = re.findall(r'\\b[A-Z][a-z]{2,}\\b', sentence)\n",
    "    if caps:\n",
    "        candidates.append(f'Who or what is {caps[0]}?')\n",
    "    # Generic What template\n",
    "    words = sentence.split()\n",
    "    if len(words) >= 4:\n",
    "        subj = ' '.join(words[:2])\n",
    "        candidates.append(f'What can be said about {subj}?')\n",
    "    return candidates\n",
    "\n",
    "sample_q_cands = generate_question(cands[0], sample_row[sample_row['answer']])\n",
    "print('Generated question candidates:')\n",
    "for q in sample_q_cands:\n",
    "    print(f'  - {q}')"
]))

cells.append(code([
    "# ── 6c. Question ranker (LinearSVC on candidate features) ──\n",
    "def candidate_features(question_text, article, answer):\n",
    "    q_len = len(question_text.split())\n",
    "    starts_wh = int(question_text.lower().split()[0] in ['who','what','where','when','why','how','which'] if question_text.split() else 0)\n",
    "    q_toks = set(clean_text(question_text).split())\n",
    "    art_toks = set(clean_text(article).split())\n",
    "    ans_toks = set(clean_text(answer).split())\n",
    "    overlap_art = len(q_toks & art_toks) / max(len(q_toks), 1)\n",
    "    overlap_ans = len(q_toks & ans_toks) / max(len(q_toks), 1)\n",
    "    return [q_len, starts_wh, overlap_art, overlap_ans]\n",
    "\n",
    "# Build training set: positive = RACE questions, negative = garbled sentences\n",
    "pos_rows = train_df.sample(min(1000, len(train_df)), random_state=42)\n",
    "X_qrank, y_qrank = [], []\n",
    "for _, r in pos_rows.iterrows():\n",
    "    ans = r[r['answer']]\n",
    "    X_qrank.append(candidate_features(r['question'], r['article'], ans))\n",
    "    y_qrank.append(1)\n",
    "    # Negative: garbled sentence (just reversed words of a candidate sentence)\n",
    "    garbled = ' '.join(r['article'].split()[:8][::-1]) + '?'\n",
    "    X_qrank.append(candidate_features(garbled, r['article'], ans))\n",
    "    y_qrank.append(0)\n",
    "\n",
    "X_qrank = np.array(X_qrank); y_qrank = np.array(y_qrank)\n",
    "q_ranker = LinearSVC(max_iter=1000)\n",
    "q_ranker.fit(X_qrank, y_qrank)\n",
    "print(f'Question ranker trained. Train acc: {accuracy_score(y_qrank, q_ranker.predict(X_qrank)):.4f}')\n",
    "joblib.dump(q_ranker, f'{MODELS_A_DIR}/q_ranker.pkl')"
]))

cells.append(code([
    "# ── 6d. Show 5 example (article snippet, generated Q, gold Q) triples ──\n",
    "print('\\n=== Example Generated vs Gold Questions ===')\n",
    "for i in range(min(5, len(train_df))):\n",
    "    r = train_df.iloc[i]\n",
    "    ans = r[r['answer']]\n",
    "    sents = score_sentences(r['article'], ans, top_k=1)\n",
    "    if not sents: continue\n",
    "    gen_qs = generate_question(sents[0], ans)\n",
    "    if not gen_qs: continue\n",
    "    # Rank\n",
    "    feats = [candidate_features(q, r['article'], ans) for q in gen_qs]\n",
    "    scores = q_ranker.decision_function(feats)\n",
    "    best_q = gen_qs[np.argmax(scores)]\n",
    "    print(f\"\\nArticle: ...{r['article'][:80]}...\")\n",
    "    print(f\"Generated Q : {best_q}\")\n",
    "    print(f\"Gold Q      : {r['question']}\")"
]))

# ─── SECTION 7 ── Model B ─────────────────────────────────────────────────
cells.append(md(["## Section 7 — Model B: Distractor & Hint Generation"]))

cells.append(md(["### 7a–7c. Distractor Ranker"]))

cells.append(code([
    "# ── 7a. Candidate extraction: n-grams from article ──\n",
    "def extract_candidates(article, answer, max_ngram=3):\n",
    "    tokens = clean_text(article).split()\n",
    "    ans_clean = clean_text(answer)\n",
    "    candidates = set()\n",
    "    for n in range(1, max_ngram+1):\n",
    "        for i in range(len(tokens)-n+1):\n",
    "            phrase = ' '.join(tokens[i:i+n])\n",
    "            if phrase != ans_clean and len(phrase) > 2:\n",
    "                candidates.add(phrase)\n",
    "    return list(candidates)\n",
    "\n",
    "# Test\n",
    "r0 = train_df.iloc[0]\n",
    "a0 = r0[r0['answer']]\n",
    "cands0 = extract_candidates(r0['article'], a0)\n",
    "print(f'Extracted {len(cands0)} candidates for row 0. Examples: {cands0[:5]}')"
]))

cells.append(code([
    "# ── 7b. Feature engineering per candidate ──\n",
    "dist_vec = CountVectorizer(binary=True, max_features=3000)\n",
    "dist_vec.fit(train_df['article_clean'].tolist() + [clean_text(v) for col in ['A','B','C','D'] for v in train_df[col]])\n",
    "\n",
    "def distractor_features(candidate, answer, article):\n",
    "    from sklearn.metrics.pairwise import cosine_similarity as cs\n",
    "    cand_vec = dist_vec.transform([candidate])\n",
    "    ans_vec  = dist_vec.transform([clean_text(answer)])\n",
    "    art_vec2 = dist_vec.transform([clean_text(article)])\n",
    "\n",
    "    cosine_ans  = cs(cand_vec, ans_vec)[0,0]\n",
    "    cosine_art  = cs(cand_vec, art_vec2)[0,0]\n",
    "\n",
    "    art_tokens = clean_text(article).split()\n",
    "    passage_freq = art_tokens.count(candidate.split()[0]) / max(len(art_tokens), 1)\n",
    "\n",
    "    char_match = sum(1 for a,b in zip(candidate, clean_text(answer)) if a==b) / max(len(clean_text(answer)),1)\n",
    "    length_ratio = len(candidate.split()) / max(len(clean_text(answer).split()), 1)\n",
    "\n",
    "    return [cosine_ans, cosine_art, passage_freq, char_match, length_ratio]\n",
    "\n",
    "print('Distractor feature function defined.')\n",
    "print('Test features:', distractor_features(cands0[0], a0, r0['article']))"
]))

cells.append(code([
    "# ── 7c. Build training data for distractor ranker ──\n",
    "print('Building distractor ranker training data (sampling rows)...')\n",
    "DIST_SAMPLE = min(500, len(train_df))\n",
    "dist_X, dist_y = [], []\n",
    "\n",
    "for _, row in train_df.sample(DIST_SAMPLE, random_state=42).iterrows():\n",
    "    correct_ans = row[row['answer']]\n",
    "    distractors = [row[o] for o in ['A','B','C','D'] if o != row['answer']]\n",
    "    article = row['article']\n",
    "\n",
    "    candidates = extract_candidates(article, correct_ans, max_ngram=2)\n",
    "    if len(candidates) < 3:\n",
    "        continue\n",
    "\n",
    "    for cand in candidates[:30]:  # limit to 30 candidates per row\n",
    "        feats = distractor_features(cand, correct_ans, article)\n",
    "        # Label 1 if this candidate matches one of the actual distractors\n",
    "        label = int(any(cand in clean_text(d) or clean_text(d) in cand for d in distractors))\n",
    "        dist_X.append(feats)\n",
    "        dist_y.append(label)\n",
    "\n",
    "dist_X = np.array(dist_X); dist_y = np.array(dist_y)\n",
    "print(f'Distractor training set: {dist_X.shape}, positive rate: {dist_y.mean():.3f}')"
]))

cells.append(code([
    "# Train distractor ranker\n",
    "dist_ranker = LogisticRegression(max_iter=500, C=1.0)\n",
    "dist_ranker.fit(dist_X, dist_y)\n",
    "dist_train_acc = accuracy_score(dist_y, dist_ranker.predict(dist_X))\n",
    "print(f'Distractor ranker train accuracy: {dist_train_acc:.4f}')\n",
    "\n",
    "joblib.dump(dist_ranker, f'{MODELS_B_DIR}/distractor_ranker.pkl')\n",
    "joblib.dump(dist_vec,    f'{MODELS_B_DIR}/vectorizer_b.pkl')\n",
    "print('Distractor ranker saved.')"
]))

cells.append(code([
    "# ── Evaluate on val set: Precision@3, Recall@3, F1@3 ──\n",
    "print('Evaluating distractor ranker on validation set...')\n",
    "VAL_EVAL = min(200, len(val_df))\n",
    "p3_scores, r3_scores = [], []\n",
    "\n",
    "for _, row in val_df.sample(VAL_EVAL, random_state=42).iterrows():\n",
    "    correct_ans = row[row['answer']]\n",
    "    gold_distractors = {clean_text(row[o]) for o in ['A','B','C','D'] if o != row['answer']}\n",
    "    candidates = extract_candidates(row['article'], correct_ans, max_ngram=2)\n",
    "    if len(candidates) < 3:\n",
    "        continue\n",
    "\n",
    "    feats = [distractor_features(c, correct_ans, row['article']) for c in candidates[:50]]\n",
    "    scores = dist_ranker.predict_proba(feats)[:,1]\n",
    "\n",
    "    # Diversity penalty\n",
    "    ranked = [candidates[i] for i in np.argsort(scores)[::-1]]\n",
    "    selected = []\n",
    "    for cand in ranked:\n",
    "        if len(selected) == 3: break\n",
    "        if not selected:\n",
    "            selected.append(cand)\n",
    "        else:\n",
    "            cand_vec = dist_vec.transform([cand])\n",
    "            too_similar = any(\n",
    "                cosine_similarity(cand_vec, dist_vec.transform([s]))[0,0] > 0.8\n",
    "                for s in selected\n",
    "            )\n",
    "            if not too_similar:\n",
    "                selected.append(cand)\n",
    "\n",
    "    if len(selected) < 3:\n",
    "        selected += ranked[:3-len(selected)]\n",
    "    selected = selected[:3]\n",
    "\n",
    "    sel_set = set(selected)\n",
    "    tp = len(sel_set & gold_distractors)\n",
    "    p3_scores.append(tp / 3)\n",
    "    r3_scores.append(tp / max(len(gold_distractors), 1))\n",
    "\n",
    "dist_p3 = np.mean(p3_scores)\n",
    "dist_r3 = np.mean(r3_scores)\n",
    "dist_f3 = 2 * dist_p3 * dist_r3 / max(dist_p3 + dist_r3, 1e-9)\n",
    "print(f'Distractor Ranker — Precision@3: {dist_p3:.4f}, Recall@3: {dist_r3:.4f}, F1@3: {dist_f3:.4f}')"
]))

cells.append(code([
    "# Confusion Matrix for distractor ranker on labelled dataset\n",
    "from sklearn.model_selection import train_test_split as tts\n",
    "X_dr_train, X_dr_val, y_dr_train, y_dr_val = tts(dist_X, dist_y, test_size=0.2, random_state=42)\n",
    "dist_ranker2 = LogisticRegression(max_iter=500).fit(X_dr_train, y_dr_train)\n",
    "dr_pred = dist_ranker2.predict(X_dr_val)\n",
    "cm_dist = confusion_matrix(y_dr_val, dr_pred)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(5,4))\n",
    "sns.heatmap(cm_dist, annot=True, fmt='d', cmap='Blues', ax=ax,\n",
    "            xticklabels=['Not Distractor','Distractor'], yticklabels=['Not Distractor','Distractor'])\n",
    "ax.set_title('Distractor Ranker Confusion Matrix')\n",
    "ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{FIGURES_DIR}/10_distractor_cm.png', dpi=100)\n",
    "plt.show()\n",
    "dist_ranker_acc = accuracy_score(y_dr_val, dr_pred)\n",
    "print(f'Distractor Ranker Accuracy (hold-out): {dist_ranker_acc:.4f}')"
]))

cells.append(md(["### 7d. Frequency-Based Fallback Distractor Generation"]))

cells.append(code([
    "def freq_fallback_distractors(article, correct_answer, n=3):\n",
    "    tokens = clean_text(article).split()\n",
    "    freq = Counter(tokens)\n",
    "    ans_tokens = set(clean_text(correct_answer).split())\n",
    "    # High-freq tokens that are NOT in the answer\n",
    "    stop_words = {'the','a','an','is','was','are','were','of','in','to','and','or','it',\n",
    "                  'for','on','with','at','by','as','he','she','they','we','this','that'}\n",
    "    candidates = [\n",
    "        tok for tok, cnt in freq.most_common(100)\n",
    "        if tok not in ans_tokens and tok not in stop_words and len(tok) > 3\n",
    "    ]\n",
    "    return candidates[:n]\n",
    "\n",
    "# Test\n",
    "fb = freq_fallback_distractors(r0['article'], a0)\n",
    "print('Frequency-based fallback distractors:', fb)"
]))

cells.append(md(["### 7e. Extractive Hint Generator"]))

cells.append(code([
    "# Score sentences by keyword overlap with question\n",
    "def get_hints(article, question, n=3):\n",
    "    sentences = [s.strip() for s in re.split(r'[.!?]', article) if len(s.strip()) > 15]\n",
    "    q_toks = set(clean_text(question).split())\n",
    "    stop = {'the','a','an','is','was','are','were','of','in','to','and','or'}\n",
    "    q_toks -= stop\n",
    "    scored = []\n",
    "    for i, s in enumerate(sentences):\n",
    "        s_toks = set(clean_text(s).split()) - stop\n",
    "        score = len(q_toks & s_toks) / max(len(q_toks), 1)\n",
    "        scored.append((score, i, s))\n",
    "    scored.sort(key=lambda x: x[0])\n",
    "    # Hint 1 = least overlap (general), Hint 3 = most overlap (specific)\n",
    "    result = [s for _, _, s in scored]\n",
    "    step = max(len(result)//3, 1)\n",
    "    hints = [result[0], result[min(step, len(result)-1)], result[min(2*step, len(result)-1)]]\n",
    "    # Ensure 3 unique non-empty hints\n",
    "    seen = set()\n",
    "    unique = []\n",
    "    for h in hints:\n",
    "        if h and h not in seen:\n",
    "            seen.add(h)\n",
    "            unique.append(h)\n",
    "    while len(unique) < 3:\n",
    "        unique.append('(Refer to the passage for more context.)')\n",
    "    return unique[:3]\n",
    "\n",
    "test_hints = get_hints(r0['article'], r0['question'])\n",
    "print('Hint 1 (general)  :', test_hints[0][:100])\n",
    "print('Hint 2 (mid)      :', test_hints[1][:100])\n",
    "print('Hint 3 (specific) :', test_hints[2][:100])"
]))

cells.append(code([
    "# ── Train LogisticRegression hint scorer ──\n",
    "HINT_SAMPLE = min(500, len(train_df))\n",
    "hint_X, hint_y = [], []\n",
    "\n",
    "for _, row in train_df.sample(HINT_SAMPLE, random_state=42).iterrows():\n",
    "    article = row['article']\n",
    "    question = row['question']\n",
    "    correct_ans = row[row['answer']]\n",
    "    sentences = [s.strip() for s in re.split(r'[.!?]', article) if len(s.strip()) > 15]\n",
    "    ans_toks = set(clean_text(correct_ans).split())\n",
    "    q_toks   = set(clean_text(question).split())\n",
    "\n",
    "    for pos, sent in enumerate(sentences[:15]):\n",
    "        s_toks = set(clean_text(sent).split())\n",
    "        kw_overlap  = len(q_toks & s_toks) / max(len(q_toks), 1)\n",
    "        ans_overlap = len(ans_toks & s_toks) / max(len(ans_toks), 1)\n",
    "        pos_norm    = pos / max(len(sentences), 1)\n",
    "        sent_len    = len(sent.split())\n",
    "        hint_X.append([kw_overlap, ans_overlap, pos_norm, sent_len])\n",
    "        hint_y.append(1 if ans_overlap > 0.3 else 0)\n",
    "\n",
    "hint_X = np.array(hint_X); hint_y = np.array(hint_y)\n",
    "hint_scorer = LogisticRegression(max_iter=500)\n",
    "hint_scorer.fit(hint_X, hint_y)\n",
    "print(f'Hint scorer trained. Train acc: {accuracy_score(hint_y, hint_scorer.predict(hint_X)):.4f}')\n",
    "\n",
    "# R² score for regression interpretation\n",
    "from sklearn.linear_model import LinearRegression\n",
    "hint_reg = LinearRegression()\n",
    "hint_reg.fit(hint_X, hint_y.astype(float))\n",
    "hint_r2 = r2_score(hint_y, hint_reg.predict(hint_X))\n",
    "print(f'Hint scorer R²: {hint_r2:.4f}')\n",
    "\n",
    "# Precision@1\n",
    "hint_p1_scores = []\n",
    "HINT_EVAL = min(200, len(val_df))\n",
    "for _, row in val_df.sample(HINT_EVAL, random_state=42).iterrows():\n",
    "    sentences = [s.strip() for s in re.split(r'[.!?]', row['article']) if len(s.strip())>15]\n",
    "    if not sentences: continue\n",
    "    q_toks  = set(clean_text(row['question']).split())\n",
    "    ans_toks= set(clean_text(row[row['answer']]).split())\n",
    "    feats = []\n",
    "    for pos, sent in enumerate(sentences[:15]):\n",
    "        s_toks = set(clean_text(sent).split())\n",
    "        feats.append([len(q_toks&s_toks)/max(len(q_toks),1),\n",
    "                      len(ans_toks&s_toks)/max(len(ans_toks),1),\n",
    "                      pos/max(len(sentences),1), len(sent.split())])\n",
    "    scores = hint_scorer.predict_proba(feats)[:,1]\n",
    "    best_sent = sentences[np.argmax(scores)]\n",
    "    gold_overlap = len(set(clean_text(best_sent).split()) & ans_toks) / max(len(ans_toks),1)\n",
    "    hint_p1_scores.append(1 if gold_overlap > 0.2 else 0)\n",
    "\n",
    "hint_p1 = np.mean(hint_p1_scores)\n",
    "print(f'Hint scorer Precision@1: {hint_p1:.4f}')\n",
    "\n",
    "joblib.dump(hint_scorer, f'{MODELS_B_DIR}/hint_scorer.pkl')\n",
    "print('Hint scorer saved.')"
]))

# ─── SECTION 8 ── Final Evaluation ────────────────────────────────────────
cells.append(md(["## Section 8 — Final Evaluation Summary"]))

cells.append(code([
    "# ══════════════════════════════════════════════════════\n",
    "# FINAL RESULTS TABLE\n",
    "# ══════════════════════════════════════════════════════\n",
    "\n",
    "# ── Evaluate all Model A classifiers on TEST set ──\n",
    "print('Evaluating on TEST set...')\n",
    "\n",
    "lr_test_pred  = lr_model.predict(X_test)\n",
    "lr_test_proba = lr_model.predict_proba(X_test)[:,1]\n",
    "svm_test_pred  = svm_model.predict(X_test)\n",
    "svm_test_proba = svm_model.predict_proba(X_test)[:,1]\n",
    "rf_test_pred   = rf_model.predict(X_lex_test)\n",
    "rf_test_proba  = rf_model.predict_proba(X_lex_test)[:,1]\n",
    "ens_test_proba = (lr_test_proba + svm_test_proba + rf_test_proba) / 3\n",
    "ens_test_pred  = (ens_test_proba >= 0.5).astype(int)\n",
    "\n",
    "test_results = {\n",
    "    'Logistic Regression': {\n",
    "        'acc': accuracy_score(y_test, lr_test_pred),\n",
    "        'f1':  f1_score(y_test, lr_test_pred, average='macro'),\n",
    "        'em':  exact_match(y_test, lr_test_proba)\n",
    "    },\n",
    "    'SVM (Calibrated)': {\n",
    "        'acc': accuracy_score(y_test, svm_test_pred),\n",
    "        'f1':  f1_score(y_test, svm_test_pred, average='macro'),\n",
    "        'em':  exact_match(y_test, svm_test_proba)\n",
    "    },\n",
    "    'Random Forest': {\n",
    "        'acc': accuracy_score(y_test, rf_test_pred),\n",
    "        'f1':  f1_score(y_test, rf_test_pred, average='macro'),\n",
    "        'em':  exact_match(y_test, rf_test_proba)\n",
    "    },\n",
    "    'Ensemble (Soft Vote)': {\n",
    "        'acc': accuracy_score(y_test, ens_test_pred),\n",
    "        'f1':  f1_score(y_test, ens_test_pred, average='macro'),\n",
    "        'em':  exact_match(y_test, ens_test_proba)\n",
    "    },\n",
    "}\n",
    "\n",
    "print('\\n=== MODEL A — ANSWER VERIFICATION ===')\n",
    "print(f\"{'Model':<25} | {'Val Acc':>7} | {'Val F1':>6} | {'Val EM':>6} | {'Test Acc':>8} | {'Test F1':>7} | {'Test EM':>7}\")\n",
    "print('-'*80)\n",
    "val_res = results\n",
    "for mname, tr in test_results.items():\n",
    "    vr = val_res.get(mname, {'accuracy':0,'f1':0,'em':0})\n",
    "    ve = vr['em'] if isinstance(vr['em'], float) else 0.0\n",
    "    print(f\"{mname:<25} | {vr['accuracy']:>7.4f} | {vr['f1']:>6.4f} | {ve:>6.4f} | {tr['acc']:>8.4f} | {tr['f1']:>7.4f} | {tr['em']:>7.4f}\")"
]))

cells.append(code([
    "print('\\n=== MODEL B — DISTRACTOR GENERATION ===')\n",
    "print(f\"{'Metric':<20} | {'Value':>8}\")\n",
    "print('-'*35)\n",
    "print(f\"{'Precision@3':<20} | {dist_p3:>8.4f}\")\n",
    "print(f\"{'Recall@3':<20} | {dist_r3:>8.4f}\")\n",
    "print(f\"{'F1@3':<20} | {dist_f3:>8.4f}\")\n",
    "print(f\"{'Ranker Accuracy':<20} | {dist_ranker_acc:>8.4f}\")\n",
    "\n",
    "print('\\n=== MODEL B — HINT EXTRACTION ===')\n",
    "print(f\"{'Metric':<20} | {'Value':>8}\")\n",
    "print('-'*35)\n",
    "print(f\"{'Precision@1':<20} | {hint_p1:>8.4f}\")\n",
    "print(f\"{'R² Score':<20} | {hint_r2:>8.4f}\")\n",
    "\n",
    "print('\\n=== UNSUPERVISED / SEMI-SUPERVISED ===')\n",
    "print(f\"{'Metric':<30} | {'Value':>8}\")\n",
    "print('-'*45)\n",
    "print(f\"{'K-Means Silhouette Score':<30} | {sil_score:>8.4f}\")\n",
    "print(f\"{'K-Means Purity':<30} | {purity:>8.4f}\")\n",
    "print(f\"{'GMM Silhouette Score':<30} | {sil_gmm:>8.4f}\")\n",
    "print(f\"{'GMM Log-Likelihood':<30} | {log_lik:>8.4f}\")\n",
    "print(f\"{'Label Propagation F1 (unlabeled)':<30} | {lp_f1:>8.4f}\")"
]))

# ─── SECTION 9 ── Export src/ scripts ─────────────────────────────────────
cells.append(md(["## Section 9 — Export src/ Scripts"]))

cells.append(code([
    "%%writefile ../src/evaluate.py\n",
    "\"\"\"evaluate.py — Metric computation utilities.\"\"\"\n",
    "import numpy as np\n",
    "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, r2_score\n",
    "\n",
    "\n",
    "def compute_metrics(y_true, y_pred, y_proba=None, n_options=4):\n",
    "    metrics = {\n",
    "        'accuracy':  accuracy_score(y_true, y_pred),\n",
    "        'macro_f1':  f1_score(y_true, y_pred, average='macro', zero_division=0),\n",
    "        'precision': precision_score(y_true, y_pred, average='macro', zero_division=0),\n",
    "        'recall':    recall_score(y_true, y_pred, average='macro', zero_division=0),\n",
    "        'confusion_matrix': confusion_matrix(y_true, y_pred).tolist(),\n",
    "    }\n",
    "    if y_proba is not None:\n",
    "        n = len(y_true) // n_options\n",
    "        correct = sum(\n",
    "            np.argmax(y_proba[i*n_options:(i+1)*n_options]) == np.argmax(y_true[i*n_options:(i+1)*n_options])\n",
    "            for i in range(n)\n",
    "            if y_true[i*n_options:(i+1)*n_options].sum() > 0\n",
    "        )\n",
    "        metrics['exact_match'] = correct / max(n, 1)\n",
    "    return metrics\n"
]))

cells.append(code([
    "%%writefile ../src/model_a_train.py\n",
    "\"\"\"model_a_train.py — Train all Model A classifiers.\"\"\"\n",
    "import os, sys, time, warnings\n",
    "import numpy as np\n",
    "import joblib\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "sys.path.insert(0, os.path.dirname(__file__))\n",
    "from preprocessing import load_features\n",
    "from evaluate import compute_metrics\n",
    "\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import LinearSVC\n",
    "from sklearn.calibration import CalibratedClassifierCV\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from scipy.sparse import load_npz\n",
    "\n",
    "PROCESSED = 'data/processed'\n",
    "MODELS_A  = 'models/model_a/traditional'\n",
    "\n",
    "\n",
    "def main():\n",
    "    X_tr, X_va, X_te, y_tr, y_va, y_te = load_features(PROCESSED)\n",
    "    # Lexical cols are last 5\n",
    "    X_lex_tr = X_tr[:, -5:].toarray()\n",
    "    X_lex_va = X_va[:, -5:].toarray()\n",
    "    X_lex_te = X_te[:, -5:].toarray()\n",
    "\n",
    "    classifiers = [\n",
    "        ('lr',  LogisticRegression(max_iter=1000, C=1.0, solver='saga', n_jobs=-1), X_tr, X_va),\n",
    "        ('svm', CalibratedClassifierCV(LinearSVC(max_iter=2000), cv=3), X_tr, X_va),\n",
    "        ('rf',  RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1), X_lex_tr, X_lex_va),\n",
    "    ]\n",
    "    for name, clf, Xtr, Xva in classifiers:\n",
    "        t0 = time.time()\n",
    "        clf.fit(Xtr, y_tr)\n",
    "        elapsed = time.time() - t0\n",
    "        preds = clf.predict(Xva)\n",
    "        m = compute_metrics(y_va, preds)\n",
    "        print(f'{name}: acc={m[\"accuracy\"]:.4f}, f1={m[\"macro_f1\"]:.4f}, time={elapsed:.1f}s')\n",
    "        joblib.dump(clf, os.path.join(MODELS_A, f'{name}_model.pkl'))\n",
    "    print('All Model A classifiers trained and saved.')\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n"
]))

cells.append(code([
    "%%writefile ../src/model_b_train.py\n",
    "\"\"\"model_b_train.py — Train Model B (distractor ranker + hint scorer).\"\"\"\n",
    "import os, sys, re, string, warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import joblib\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from collections import Counter\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "PROCESSED = 'data/processed'\n",
    "MODELS_B  = 'models/model_b/traditional'\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    text = str(text).lower()\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    return re.sub(r'\\s+', ' ', text).strip()\n",
    "\n",
    "\n",
    "def extract_candidates(article, answer, max_ngram=2):\n",
    "    tokens = clean_text(article).split()\n",
    "    ans_clean = clean_text(answer)\n",
    "    cands = set()\n",
    "    for n in range(1, max_ngram+1):\n",
    "        for i in range(len(tokens)-n+1):\n",
    "            p = ' '.join(tokens[i:i+n])\n",
    "            if p != ans_clean and len(p) > 2:\n",
    "                cands.add(p)\n",
    "    return list(cands)\n",
    "\n",
    "\n",
    "def main():\n",
    "    train_df = pd.read_csv(os.path.join('data/raw', 'train.csv'))\n",
    "    # Build vocab\n",
    "    dist_vec = CountVectorizer(binary=True, max_features=3000)\n",
    "    dist_vec.fit(train_df['article'].apply(clean_text).tolist())\n",
    "    joblib.dump(dist_vec, os.path.join(MODELS_B, 'vectorizer_b.pkl'))\n",
    "\n",
    "    SAMPLE = min(500, len(train_df))\n",
    "    dist_X, dist_y = [], []\n",
    "    for _, row in train_df.sample(SAMPLE, random_state=42).iterrows():\n",
    "        correct_ans = row[row['answer']]\n",
    "        distractors = [row[o] for o in ['A','B','C','D'] if o != row['answer']]\n",
    "        cands = extract_candidates(row['article'], correct_ans)\n",
    "        if len(cands) < 3: continue\n",
    "        for cand in cands[:30]:\n",
    "            cv = dist_vec.transform([cand])\n",
    "            av = dist_vec.transform([clean_text(correct_ans)])\n",
    "            cos = cosine_similarity(cv, av)[0,0]\n",
    "            freq = clean_text(row['article']).split().count(cand.split()[0]) / max(len(clean_text(row['article']).split()),1)\n",
    "            char = sum(1 for a,b in zip(cand, clean_text(correct_ans)) if a==b)/max(len(clean_text(correct_ans)),1)\n",
    "            lr = len(cand.split())/max(len(clean_text(correct_ans).split()),1)\n",
    "            cart = cosine_similarity(cv, dist_vec.transform([clean_text(row['article'])]))[0,0]\n",
    "            label = int(any(cand in clean_text(d) or clean_text(d) in cand for d in distractors))\n",
    "            dist_X.append([cos, cart, freq, char, lr])\n",
    "            dist_y.append(label)\n",
    "    dist_X = np.array(dist_X); dist_y = np.array(dist_y)\n",
    "    ranker = LogisticRegression(max_iter=500).fit(dist_X, dist_y)\n",
    "    joblib.dump(ranker, os.path.join(MODELS_B, 'distractor_ranker.pkl'))\n",
    "    print(f'Distractor ranker trained. Acc: {accuracy_score(dist_y, ranker.predict(dist_X)):.4f}')\n",
    "\n",
    "    hint_X, hint_y = [], []\n",
    "    for _, row in train_df.sample(SAMPLE, random_state=42).iterrows():\n",
    "        sents = [s.strip() for s in re.split(r'[.!?]', row['article']) if len(s.strip())>15]\n",
    "        qt = set(clean_text(row['question']).split())\n",
    "        at = set(clean_text(row[row['answer']]).split())\n",
    "        for pos, sent in enumerate(sents[:15]):\n",
    "            st = set(clean_text(sent).split())\n",
    "            hint_X.append([len(qt&st)/max(len(qt),1), len(at&st)/max(len(at),1), pos/max(len(sents),1), len(sent.split())])\n",
    "            hint_y.append(1 if len(at&st)/max(len(at),1) > 0.3 else 0)\n",
    "    hint_X = np.array(hint_X); hint_y = np.array(hint_y)\n",
    "    hint_scorer = LogisticRegression(max_iter=500).fit(hint_X, hint_y)\n",
    "    joblib.dump(hint_scorer, os.path.join(MODELS_B, 'hint_scorer.pkl'))\n",
    "    print('Hint scorer trained and saved.')\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()\n"
]))

cells.append(code([
    "%%writefile ../src/inference.py\n",
    "\"\"\"inference.py — Unified inference API.\"\"\"\n",
    "import os, re, string, time, warnings\n",
    "import numpy as np\n",
    "import joblib\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from scipy.sparse import hstack, csr_matrix\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "from collections import Counter\n",
    "\n",
    "_MODELS = {}\n",
    "\n",
    "BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n",
    "MODELS_A = os.path.join(BASE_DIR, '..', 'models', 'model_a', 'traditional')\n",
    "MODELS_B = os.path.join(BASE_DIR, '..', 'models', 'model_b', 'traditional')\n",
    "\n",
    "\n",
    "def _load_models():\n",
    "    if _MODELS: return\n",
    "    _MODELS['ohe']      = joblib.load(os.path.join(MODELS_A, 'ohe_vectorizer.pkl'))\n",
    "    _MODELS['lr']       = joblib.load(os.path.join(MODELS_A, 'lr_model.pkl'))\n",
    "    _MODELS['svm']      = joblib.load(os.path.join(MODELS_A, 'svm_model.pkl'))\n",
    "    _MODELS['rf']       = joblib.load(os.path.join(MODELS_A, 'rf_model.pkl'))\n",
    "    _MODELS['dist_vec'] = joblib.load(os.path.join(MODELS_B, 'vectorizer_b.pkl'))\n",
    "    _MODELS['dist_rk']  = joblib.load(os.path.join(MODELS_B, 'distractor_ranker.pkl'))\n",
    "    _MODELS['hint_sk']  = joblib.load(os.path.join(MODELS_B, 'hint_scorer.pkl'))\n",
    "\n",
    "\n",
    "def _clean(text):\n",
    "    text = str(text).lower()\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    return re.sub(r'\\s+', ' ', text).strip()\n",
    "\n",
    "\n",
    "def predict_answer(article, question, options):\n",
    "    \"\"\"Returns predicted answer letter ('A','B','C','D').\"\"\"\n",
    "    _load_models()\n",
    "    ohe = _MODELS['ohe']; lr = _MODELS['lr']; svm = _MODELS['svm']; rf = _MODELS['rf']\n",
    "    arts = _clean(article); qs = _clean(question)\n",
    "    texts, lex_rows = [], []\n",
    "    for opt in options:\n",
    "        os_c = _clean(opt)\n",
    "        texts.append(f'{arts} [SEP] {qs} [SEP] {os_c}')\n",
    "        at = set(arts.split()); qt = set(qs.split()); ot = set(os_c.split())\n",
    "        ol = os_c.split()\n",
    "        pos = arts.find(ol[0]) / max(len(arts),1) if ol and ol[0] in arts else 0.0\n",
    "        lex_rows.append([len(ol), len(qs.split()), len(qt&ot), len(ot&at), pos])\n",
    "    X_ohe = ohe.transform(texts)\n",
    "    art_vec = type(ohe)(binary=True, vocabulary=ohe.vocabulary_)\n",
    "    art_m = art_vec.transform([arts]*4)\n",
    "    opt_m = art_vec.transform([_clean(o) for o in options])\n",
    "    cos_f = csr_matrix(np.array([cosine_similarity(art_m[i], opt_m[i])[0,0] for i in range(4)]).reshape(-1,1))\n",
    "    lex_f = csr_matrix(np.array(lex_rows, dtype=np.float32))\n",
    "    X = hstack([X_ohe, cos_f, lex_f])\n",
    "    lr_p  = lr.predict_proba(X)[:,1]\n",
    "    svm_p = svm.predict_proba(X)[:,1]\n",
    "    rf_p  = rf.predict_proba(lex_f.toarray())[:,1]\n",
    "    scores = (lr_p + svm_p + rf_p) / 3\n",
    "    return ['A','B','C','D'][int(np.argmax(scores))]\n",
    "\n",
    "\n",
    "def generate_distractors(article, question, answer, n=3):\n",
    "    \"\"\"Returns list of 3 distractor strings.\"\"\"\n",
    "    _load_models()\n",
    "    dvec = _MODELS['dist_vec']; drk = _MODELS['dist_rk']\n",
    "    tokens = _clean(article).split()\n",
    "    ans_c = _clean(answer)\n",
    "    cands = list({' '.join(tokens[i:i+n_]) for n_ in range(1,3) for i in range(len(tokens)-n_+1)\n",
    "                  if ' '.join(tokens[i:i+n_]) != ans_c and len(' '.join(tokens[i:i+n_])) > 2})\n",
    "    if len(cands) < n:\n",
    "        freq = Counter(tokens)\n",
    "        stop = {'the','a','an','is','was','are','were','of','in','to','and','or','it'}\n",
    "        cands += [t for t,_ in freq.most_common(50) if t not in _clean(answer).split() and t not in stop][:n]\n",
    "    feats = []\n",
    "    for cand in cands[:80]:\n",
    "        cv = dvec.transform([cand]); av = dvec.transform([ans_c])\n",
    "        arv = dvec.transform([_clean(article)])\n",
    "        cos_a = cosine_similarity(cv, av)[0,0]\n",
    "        cos_r = cosine_similarity(cv, arv)[0,0]\n",
    "        freq_f = tokens.count(cand.split()[0]) / max(len(tokens),1)\n",
    "        char_f = sum(1 for a,b in zip(cand, ans_c) if a==b) / max(len(ans_c),1)\n",
    "        lr_f = len(cand.split()) / max(len(ans_c.split()),1)\n",
    "        feats.append([cos_a, cos_r, freq_f, char_f, lr_f])\n",
    "    scores = drk.predict_proba(feats)[:,1]\n",
    "    ranked = [cands[i] for i in np.argsort(scores)[::-1]]\n",
    "    selected = []\n",
    "    for cand in ranked:\n",
    "        if len(selected) == n: break\n",
    "        if not selected:\n",
    "            selected.append(cand)\n",
    "        else:\n",
    "            cv = dvec.transform([cand])\n",
    "            if not any(cosine_similarity(cv, dvec.transform([s]))[0,0] > 0.8 for s in selected):\n",
    "                selected.append(cand)\n",
    "    while len(selected) < n:\n",
    "        selected.append(ranked[len(selected)] if len(ranked) > len(selected) else 'N/A')\n",
    "    return selected[:n]\n",
    "\n",
    "\n",
    "def get_hints(article, question, n=3):\n",
    "    \"\"\"Returns list of 3 graduated hint strings.\"\"\"\n",
    "    _load_models()\n",
    "    hsk = _MODELS['hint_sk']\n",
    "    sents = [s.strip() for s in re.split(r'[.!?]', article) if len(s.strip()) > 15]\n",
    "    if not sents:\n",
    "        return ['(No hints available.)']*3\n",
    "    qt = set(_clean(question).split())\n",
    "    feats = []\n",
    "    for pos, sent in enumerate(sents[:20]):\n",
    "        st = set(_clean(sent).split())\n",
    "        feats.append([len(qt&st)/max(len(qt),1), 0.0, pos/max(len(sents),1), len(sent.split())])\n",
    "    scores = hsk.predict_proba(feats)[:,1]\n",
    "    order = np.argsort(scores)\n",
    "    step = max(len(order)//3, 1)\n",
    "    hint_sents = [sents[order[0]], sents[order[min(step, len(order)-1)]], sents[order[min(2*step, len(order)-1)]]]\n",
    "    seen, result = set(), []\n",
    "    for h in hint_sents:\n",
    "        if h not in seen: seen.add(h); result.append(h)\n",
    "    while len(result) < 3:\n",
    "        result.append('(Refer to the passage for more context.)')\n",
    "    return result[:3]\n"
]))

cells.append(code([
    "print('\\nPhase 1 COMPLETE.')\n",
    "print('All model artifacts saved.')\n",
    "print('All src/ scripts written.')\n",
    "print('\\nHandoff: Run this notebook top-to-bottom, then return the executed .ipynb for Phase 2.')"
]))

# ─── Assemble notebook JSON ────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"}
    },
    "cells": cells
}

out_path = os.path.join(os.path.dirname(__file__), 'EDA_and_Training.ipynb')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Notebook written → {out_path}')
print(f'Total cells: {len(cells)}')
